###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: laravel-versioning-api-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: laravel-versioning-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/local/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/local/phpdocker/php-fpm
      container_name: laravel-versioning-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/local/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    pma:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      container_name: laravel-versioning-api-phpmyadmin
      restart: always
      ports:
        - '8001:80'
      environment:
        PMA_HOST: mysql
